# Generated by Django 3.2.3 on 2021-06-01 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_like_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like',
        ),
    ]
