# Generated by Django 3.2.3 on 2021-05-20 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_posts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
